
package Vista;

import Controlador.Controlador;

import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JOptionPane;
import javax.swing.JTextArea;


/**
 *
 * @author facun
 */
public class VentanaGeneral extends javax.swing.JFrame
{
    private Controlador c;

    /** Creates new form VentanaGeneral */
    public VentanaGeneral(Controlador c)
    {
        initComponents();
        this.BotonAddUser.setActionCommand(Controlador.ADDUSER);
        this.BotonAddCLiente.setActionCommand(Controlador.ADDCLIENTE);
        this.BotonDeletUser.setActionCommand(Controlador.DELETUSER);
        this.BotonAddGrupo.setActionCommand(Controlador.ADDGRUPO);
        this.BotonDeletCliente.setActionCommand(Controlador.DELETCLIENTE);
        this.BotonInformPeriodCliente.setActionCommand(Controlador.INFORMTAREACLIENTE);
        this.BotonInformTodasATareas.setActionCommand(Controlador.INFORMATAREAS);
        this.BotonDeleteGrupo.setActionCommand(Controlador.DELETEGRUPO);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.c = c;
        this.addWindowListener(new WindowAdapter()
        {
            public void windowClosing(WindowEvent evt)
            {
                c.terminar();

            }
        });
    }

    public VentanaGeneral()
    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents()//GEN-BEGIN:initComponents
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        BotonAddUser = new javax.swing.JButton();
        BotonAddCLiente = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        BotonAddGrupo = new javax.swing.JButton();
        BotonInformPeriodCliente = new javax.swing.JButton();
        BotonInformColabor = new javax.swing.JButton();
        BotonInformUser = new javax.swing.JButton();
        BotonInformTodasATareas = new javax.swing.JButton();
        BotonDeletUser = new javax.swing.JButton();
        BotonDeleteGrupo = new javax.swing.JButton();
        BotonDeleteTarea = new javax.swing.JButton();
        BotonDeletCliente = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(801, 740));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 100));

        BotonAddUser.setText("Agregar Usuario");
        BotonAddUser.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BotonAddUserActionPerformed(evt);
            }
        });
        jPanel2.add(BotonAddUser);

        BotonAddCLiente.setText("Agregar Cliente");
        BotonAddCLiente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BotonAddCLienteActionPerformed(evt);
            }
        });
        jPanel2.add(BotonAddCLiente);

        jButton3.setText("Agregar servicio");
        jPanel2.add(jButton3);

        BotonAddGrupo.setText("Agregar grupo");
        jPanel2.add(BotonAddGrupo);

        BotonInformPeriodCliente.setText("Informe de tareas en un periodo para un cliente ");
        jPanel2.add(BotonInformPeriodCliente);

        BotonInformColabor.setText("Informe de tareas para un colaborador");
        jPanel2.add(BotonInformColabor);

        BotonInformUser.setText("Informe de tareas realizadas por un usuario");
        jPanel2.add(BotonInformUser);

        BotonInformTodasATareas.setText("Informe de todas las tareas no cerradas");
        jPanel2.add(BotonInformTodasATareas);

        BotonDeletUser.setText("Eliminar Usuario");
        jPanel2.add(BotonDeletUser);

        BotonDeleteGrupo.setText("Eliminar Grupo");
        jPanel2.add(BotonDeleteGrupo);

        BotonDeleteTarea.setText("Eliminar tarea");
        jPanel2.add(BotonDeleteTarea);

        BotonDeletCliente.setText("Eliminar Ciente");
        jPanel2.add(BotonDeletCliente);

        jPanel3.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void BotonAddCLienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BotonAddCLienteActionPerformed
    {//GEN-HEADEREND:event_BotonAddCLienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAddCLienteActionPerformed

    private void BotonAddUserActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BotonAddUserActionPerformed
    {//GEN-HEADEREND:event_BotonAddUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAddUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaGeneral.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaGeneral.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaGeneral.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaGeneral.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable()
            {
                public void run()
                {
                    new VentanaGeneral().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAddCLiente;
    private javax.swing.JButton BotonAddGrupo;
    private javax.swing.JButton BotonAddUser;
    private javax.swing.JButton BotonDeletCliente;
    private javax.swing.JButton BotonDeletUser;
    private javax.swing.JButton BotonDeleteGrupo;
    private javax.swing.JButton BotonInformColabor;
    private javax.swing.JButton BotonInformPeriodCliente;
    private javax.swing.JButton BotonInformTodasATareas;
    private javax.swing.JButton BotonInformUser;
    private javax.swing.JButton BotonDeleteTarea;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
    public void addActionListener(ActionListener al)
    {
        this.BotonAddUser.addActionListener(al);
        this.BotonAddCLiente.addActionListener(al);
        this.BotonDeletUser.addActionListener(al);
        this.BotonAddGrupo.addActionListener(al);
        this.BotonDeletCliente.addActionListener(al);
        this.BotonInformPeriodCliente.addActionListener(al);
        this.BotonInformTodasATareas.addActionListener(al);
        this.BotonDeleteGrupo.addActionListener(al);
    }

    public void mostrarError(String s)
    {
        JOptionPane.showMessageDialog(this, s, "Error", JOptionPane.ERROR_MESSAGE);
    }
    public void mostrarValidacion(String s,String titulo)
    {
        JOptionPane.showMessageDialog(this, s, titulo, JOptionPane.WARNING_MESSAGE);
    }

    public String IngresarTexto(String titulo, String frase)
    {
        return JOptionPane.showInputDialog(null,  frase,titulo,JOptionPane.PLAIN_MESSAGE);
    }

    public String ingresarRespuesta(String s)
    {
        return JOptionPane.showInputDialog(this, s, "Creando Respuesta", JOptionPane.PLAIN_MESSAGE);
    }
    
    public String eliminarNombre( String[] nombres,String frase)
    {
        return                     (String) JOptionPane.showInputDialog(this, frase, "Eliminar",
                                                         JOptionPane.DEFAULT_OPTION, null, nombres,
                                                         nombres[0]);
    }
    
    public JTextArea getJTextArea()
    {
        return this.jTextArea2;
    }
}
